# Generated by Django 5.2.8 on 2025-12-20 11:03

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_scholarshipapplication_renewal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='document',
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.birth_certificate_upload),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='enrollment_cert',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.enrollment_cert_upload),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='good_moral',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.good_moral_upload),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='id_photo',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.id_photo_upload),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='report_card',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.report_card_upload),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='semester',
            field=models.CharField(default='1st Semester', max_length=50),
        ),
    ]
