# Generated by Django 5.2.8 on 2025-12-20 11:27

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_scholarshipapplication_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renewal',
            name='document',
        ),
        migrations.AddField(
            model_name='renewal',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.renew_birth_certificate_upload),
        ),
        migrations.AddField(
            model_name='renewal',
            name='enrollment_cert',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.renew_enrollment_cert_upload),
        ),
        migrations.AddField(
            model_name='renewal',
            name='good_moral',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.renew_good_moral_upload),
        ),
        migrations.AddField(
            model_name='renewal',
            name='id_photo',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.renew_id_photo_upload),
        ),
        migrations.AddField(
            model_name='renewal',
            name='report_card',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.renew_report_card_upload),
        ),
    ]
