# Generated by Django 5.2.8 on 2026-01-11 16:53

import accounts.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_studentprofile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarshipapplication',
            old_name='enrollment_cert',
            new_name='enrollment_certificate',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='id_photo',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='report_card',
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='age',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='application_date',
            field=models.DateField(default=datetime.date(2003, 2, 2)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='cellphone',
            field=models.CharField(default=1211111, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='city',
            field=models.CharField(default='Antipolo', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='firstname',
            field=models.CharField(default='dar', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='middlename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='previous_school',
            field=models.CharField(default='da', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='proof_identity',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.proof_identity_upload),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='province',
            field=models.CharField(default='ads', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='scholarship_essay',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.scholarship_essay_upload),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='school_year',
            field=models.CharField(default=11111111, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='male', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='strand_course',
            field=models.CharField(default='dasda', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='street_no',
            field=models.CharField(default=1111111, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='student_number',
            field=models.CharField(default=11111111111, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='surname',
            field=models.CharField(default='das', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='transcript_records',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.transcript_records_upload),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='semester',
            field=models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('3rd', '3rd Semester'), ('4th', '4th Semester')], max_length=5),
        ),
        migrations.DeleteModel(
            name='Renewal',
        ),
    ]
