# Generated by Django 5.2.8 on 2026-01-11 20:49

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_enrollment_cert_scholarshipapplication_enrollment_certificate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('3rd', '3rd Semester'), ('4th', '4th Semester')], default='1', max_length=20)),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to=accounts.models.renew_birth_certificate_upload)),
                ('report_card', models.FileField(blank=True, null=True, upload_to=accounts.models.renew_report_card_upload)),
                ('enrollment_cert', models.FileField(blank=True, null=True, upload_to=accounts.models.renew_enrollment_cert_upload)),
                ('good_moral', models.FileField(blank=True, null=True, upload_to=accounts.models.renew_good_moral_upload)),
                ('id_photo', models.FileField(blank=True, null=True, upload_to=accounts.models.renew_id_photo_upload)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='accounts.scholarshipapplication')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'scholarship', 'semester')},
            },
        ),
    ]
