# Generated by Django 5.2.8 on 2026-01-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_renewal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='student_number',
        ),
    ]
