# Generated by Django 5.2.8 on 2025-11-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_fullname', models.CharField(max_length=55)),
                ('student_contact', models.CharField(max_length=20)),
                ('student_email', models.CharField(max_length=100)),
                ('student_grade', models.IntegerField()),
                ('student_course', models.CharField(choices=[('BSCS', 'BSCS'), ('BSAB', 'BSAB'), ('BSIT', 'BSIT')], default='BSCS', max_length=20)),
            ],
        ),
    ]
