# Generated by Django 5.2.7 on 2025-11-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='student_id',
            field=models.IntegerField(unique=True),
        ),
    ]
