# Generated by Django 5.2.7 on 2025-11-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_data_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='student_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
