# Generated by Django 5.2.8 on 2025-12-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_data_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(null=True, unique=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('course', models.CharField(choices=[('BSCS', 'BS Computer Science'), ('BSBA-FM', 'BSBA Financial Management'), ('BSBA-MM', 'BSBA Marketing Management'), ('BEED', 'BS Elementary Education'), ('BPEd', 'BS Physical Education'), ('BSTM', 'BS Tourism Management'), ('BSHM', 'BS Hospitality Management')], max_length=50, null=True)),
                ('year_level', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('id_picture', models.FileField(blank=True, null=True, upload_to='id_pictures/')),
                ('report_card', models.FileField(blank=True, null=True, upload_to='report_cards/')),
                ('good_moral', models.FileField(blank=True, null=True, upload_to='good_moral/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='student_data',
        ),
    ]
